const practiceTrials = [
  {
    id: "practice_1",
    phase: "practice",
    block_id: 0,
    trial_in_block: 1,
    condition: "practice",
    utterance: "The bottle",
    item: "bottle",
    image: "stimuli/practice_01.png",
    blindSpot: "topLeft",
    correctAnswer: "bottomRight",
  },
  {
    id: "practice_2",
    phase: "practice",
    block_id: 0,
    trial_in_block: 2,
    condition: "practice",
    utterance: "The grapes",
    item: "grapes",
    image: "stimuli/practice_02.png",
    blindSpot: "topLeft",
    correctAnswer: "topRight",
  },
  {
    id: "practice_3",
    phase: "practice",
    block_id: 0,
    trial_in_block: 3,
    condition: "practice",
    utterance: "The ring",
    item: "ring",
    image: "stimuli/practice_03.png",
    blindSpot: "topLeft",
    correctAnswer: "bottomLeft",
  },
  {
    id: "practice_4",
    phase: "practice",
    block_id: 0,
    trial_in_block: 4,
    condition: "practice",
    utterance: "The scissors",
    item: "scissors",
    image: "stimuli/practice_04.png",
    blindSpot: "topLeft",
    correctAnswer: "topRight",
  },
  {
    id: "practice_5",
    phase: "practice",
    block_id: 0,
    trial_in_block: 5,
    condition: "practice",
    utterance: "The pillow",
    item: "pillow",
    image: "stimuli/practice_05.png",
    blindSpot: "topLeft",
    correctAnswer: "bottomLeft",
  }
];

export default practiceTrials;